version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    groups:
      bundler-dependencies:
        patterns:
          - "*"

