name: Lint

on:
  pull_request:
    paths:
      - "**/*.rb"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: yettoapp/actions/setup-languages@main
        with:
          ruby: true

      - name: RuboCop
        run: bundle exec rake rubocop
